# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: digital_catalog

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console Web UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data: